[framework]
browsers = ["chromium"]
base_url = "https://automationteststore.com/"
credential_key = "automationteststore_user"
saucedemo_credential_key = "saucedemo_user"
db_path = "data/test_data.sqlite3"
